# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Publish to NuGet

on:
  push:
    branches: [ "main" ]
    paths:
      - 'popilot/**'

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - run: |
        git fetch --unshallow
    
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'
    
    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
    
    - name: Restore dependencies
      run: dotnet restore ./popilot/popilot.csproj
      
    - name: Build
      run: dotnet build ./popilot/popilot.csproj /p:Version=${{ steps.gitversion.outputs.majorMinorPatch }} --configuration Release --no-restore
      
    - name: Pack
      run: dotnet pack ./popilot/popilot.csproj /p:PackageVersion=${{ steps.gitversion.outputs.semVer }} --no-restore --configuration Release --output nupkgs

    - name: Push to NuGet
      run: dotnet nuget push "./nupkgs/*.nupkg" --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
